# Generated by Django 4.1.5 on 2023-01-24 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0002_person"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person", old_name="name", new_name="person_name",
        ),
    ]
