# Generated by Django 4.1.5 on 2023-01-31 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0005_logger"),
    ]

    operations = [
        migrations.RemoveField(model_name="menu", name="cuisine",),
    ]
