# Generated by Django 4.1.5 on 2023-02-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0006_remove_menu_cuisine"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("booking_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
